// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbabjjnitfmgdwtkomxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFiYWJqam5pdGZtZ2R3dGtvbXhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg3MDgwMzQsImV4cCI6MjA3NDI4NDAzNH0.Yw9gov8gDU9cNY01CZtR0SoMopXRLMmZBrlrtNL2YrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});